/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace CreditDecisionEngine {
  export type ParamsStruct = {
    minTransferCount: BigNumberish;
    minTotalAmount: BigNumberish;
    minConsistencyBps: BigNumberish;
    creditMultiplierBps: BigNumberish;
    maxCreditLimit: BigNumberish;
    lookbackWindowSeconds: BigNumberish;
    maxStalenessSeconds: BigNumberish;
  };

  export type ParamsStructOutput = [
    minTransferCount: bigint,
    minTotalAmount: bigint,
    minConsistencyBps: bigint,
    creditMultiplierBps: bigint,
    maxCreditLimit: bigint,
    lookbackWindowSeconds: bigint,
    maxStalenessSeconds: bigint
  ] & {
    minTransferCount: bigint;
    minTotalAmount: bigint;
    minConsistencyBps: bigint;
    creditMultiplierBps: bigint;
    maxCreditLimit: bigint;
    lookbackWindowSeconds: bigint;
    maxStalenessSeconds: bigint;
  };

  export type DecisionStruct = {
    eligible: boolean;
    creditLimit: BigNumberish;
    riskScoreBps: BigNumberish;
    rationale: string;
  };

  export type DecisionStructOutput = [
    eligible: boolean,
    creditLimit: bigint,
    riskScoreBps: bigint,
    rationale: string
  ] & {
    eligible: boolean;
    creditLimit: bigint;
    riskScoreBps: bigint;
    rationale: string;
  };
}

export declare namespace IRemittanceCreditRegistry {
  export type RemittanceStatsStruct = {
    transferCount: BigNumberish;
    totalAmount: BigNumberish;
    firstTimestamp: BigNumberish;
    lastTimestamp: BigNumberish;
    avgIntervalSeconds: BigNumberish;
    intervalConsistencyBps: BigNumberish;
  };

  export type RemittanceStatsStructOutput = [
    transferCount: bigint,
    totalAmount: bigint,
    firstTimestamp: bigint,
    lastTimestamp: bigint,
    avgIntervalSeconds: bigint,
    intervalConsistencyBps: bigint
  ] & {
    transferCount: bigint;
    totalAmount: bigint;
    firstTimestamp: bigint;
    lastTimestamp: bigint;
    avgIntervalSeconds: bigint;
    intervalConsistencyBps: bigint;
  };
}

export interface CreditDecisionEngineInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "decide"
      | "decideFromRegistry"
      | "owner"
      | "params"
      | "renounceOwnership"
      | "setParams"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DecisionComputed"
      | "OwnershipTransferred"
      | "ParamsUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "decide",
    values: [IRemittanceCreditRegistry.RemittanceStatsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "decideFromRegistry",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "params", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setParams",
    values: [CreditDecisionEngine.ParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "decide", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "decideFromRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "params", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setParams", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace DecisionComputedEvent {
  export type InputTuple = [
    borrower: AddressLike,
    eligible: boolean,
    creditLimit: BigNumberish,
    riskScoreBps: BigNumberish
  ];
  export type OutputTuple = [
    borrower: string,
    eligible: boolean,
    creditLimit: bigint,
    riskScoreBps: bigint
  ];
  export interface OutputObject {
    borrower: string;
    eligible: boolean;
    creditLimit: bigint;
    riskScoreBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ParamsUpdatedEvent {
  export type InputTuple = [params: CreditDecisionEngine.ParamsStruct];
  export type OutputTuple = [params: CreditDecisionEngine.ParamsStructOutput];
  export interface OutputObject {
    params: CreditDecisionEngine.ParamsStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CreditDecisionEngine extends BaseContract {
  connect(runner?: ContractRunner | null): CreditDecisionEngine;
  waitForDeployment(): Promise<this>;

  interface: CreditDecisionEngineInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  decide: TypedContractMethod<
    [stats: IRemittanceCreditRegistry.RemittanceStatsStruct],
    [CreditDecisionEngine.DecisionStructOutput],
    "view"
  >;

  decideFromRegistry: TypedContractMethod<
    [registry: AddressLike, borrower: AddressLike],
    [CreditDecisionEngine.DecisionStructOutput],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  params: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        minTransferCount: bigint;
        minTotalAmount: bigint;
        minConsistencyBps: bigint;
        creditMultiplierBps: bigint;
        maxCreditLimit: bigint;
        lookbackWindowSeconds: bigint;
        maxStalenessSeconds: bigint;
      }
    ],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setParams: TypedContractMethod<
    [newParams: CreditDecisionEngine.ParamsStruct],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "decide"
  ): TypedContractMethod<
    [stats: IRemittanceCreditRegistry.RemittanceStatsStruct],
    [CreditDecisionEngine.DecisionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "decideFromRegistry"
  ): TypedContractMethod<
    [registry: AddressLike, borrower: AddressLike],
    [CreditDecisionEngine.DecisionStructOutput],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "params"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        minTransferCount: bigint;
        minTotalAmount: bigint;
        minConsistencyBps: bigint;
        creditMultiplierBps: bigint;
        maxCreditLimit: bigint;
        lookbackWindowSeconds: bigint;
        maxStalenessSeconds: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setParams"
  ): TypedContractMethod<
    [newParams: CreditDecisionEngine.ParamsStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "DecisionComputed"
  ): TypedContractEvent<
    DecisionComputedEvent.InputTuple,
    DecisionComputedEvent.OutputTuple,
    DecisionComputedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ParamsUpdated"
  ): TypedContractEvent<
    ParamsUpdatedEvent.InputTuple,
    ParamsUpdatedEvent.OutputTuple,
    ParamsUpdatedEvent.OutputObject
  >;

  filters: {
    "DecisionComputed(address,bool,uint256,uint16)": TypedContractEvent<
      DecisionComputedEvent.InputTuple,
      DecisionComputedEvent.OutputTuple,
      DecisionComputedEvent.OutputObject
    >;
    DecisionComputed: TypedContractEvent<
      DecisionComputedEvent.InputTuple,
      DecisionComputedEvent.OutputTuple,
      DecisionComputedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ParamsUpdated(tuple)": TypedContractEvent<
      ParamsUpdatedEvent.InputTuple,
      ParamsUpdatedEvent.OutputTuple,
      ParamsUpdatedEvent.OutputObject
    >;
    ParamsUpdated: TypedContractEvent<
      ParamsUpdatedEvent.InputTuple,
      ParamsUpdatedEvent.OutputTuple,
      ParamsUpdatedEvent.OutputObject
    >;
  };
}
