/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace IRemittanceCreditRegistry {
  export type RemittanceStatsStruct = {
    transferCount: BigNumberish;
    totalAmount: BigNumberish;
    firstTimestamp: BigNumberish;
    lastTimestamp: BigNumberish;
    avgIntervalSeconds: BigNumberish;
    intervalConsistencyBps: BigNumberish;
  };

  export type RemittanceStatsStructOutput = [
    transferCount: bigint,
    totalAmount: bigint,
    firstTimestamp: bigint,
    lastTimestamp: bigint,
    avgIntervalSeconds: bigint,
    intervalConsistencyBps: bigint
  ] & {
    transferCount: bigint;
    totalAmount: bigint;
    firstTimestamp: bigint;
    lastTimestamp: bigint;
    avgIntervalSeconds: bigint;
    intervalConsistencyBps: bigint;
  };

  export type VerifiedTransferStruct = {
    sender: AddressLike;
    amount: BigNumberish;
    sourceTimestamp: BigNumberish;
    sourceTxHash: BytesLike;
    recordedAt: BigNumberish;
  };

  export type VerifiedTransferStructOutput = [
    sender: string,
    amount: bigint,
    sourceTimestamp: bigint,
    sourceTxHash: string,
    recordedAt: bigint
  ] & {
    sender: string;
    amount: bigint;
    sourceTimestamp: bigint;
    sourceTxHash: string;
    recordedAt: bigint;
  };
}

export interface RemittanceCreditRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getStats"
      | "getTransfers"
      | "getTransfersPaginated"
      | "isTransferRecorded"
      | "owner"
      | "recordVerifiedTransfer"
      | "recorder"
      | "renounceOwnership"
      | "setRecorder"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "RecorderUpdated"
      | "VerifiedTransferRecorded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getStats",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTransfers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTransfersPaginated",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isTransferRecorded",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordVerifiedTransfer",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "recorder", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setRecorder",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "getStats", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTransfers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransfersPaginated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTransferRecorded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordVerifiedTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "recorder", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRecorder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecorderUpdatedEvent {
  export type InputTuple = [
    previousRecorder: AddressLike,
    newRecorder: AddressLike
  ];
  export type OutputTuple = [previousRecorder: string, newRecorder: string];
  export interface OutputObject {
    previousRecorder: string;
    newRecorder: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifiedTransferRecordedEvent {
  export type InputTuple = [
    borrower: AddressLike,
    sender: AddressLike,
    amount: BigNumberish,
    sourceTimestamp: BigNumberish,
    sourceTxHash: BytesLike
  ];
  export type OutputTuple = [
    borrower: string,
    sender: string,
    amount: bigint,
    sourceTimestamp: bigint,
    sourceTxHash: string
  ];
  export interface OutputObject {
    borrower: string;
    sender: string;
    amount: bigint;
    sourceTimestamp: bigint;
    sourceTxHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RemittanceCreditRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): RemittanceCreditRegistry;
  waitForDeployment(): Promise<this>;

  interface: RemittanceCreditRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getStats: TypedContractMethod<
    [borrower: AddressLike, lookbackWindowSeconds: BigNumberish],
    [IRemittanceCreditRegistry.RemittanceStatsStructOutput],
    "view"
  >;

  getTransfers: TypedContractMethod<
    [borrower: AddressLike],
    [IRemittanceCreditRegistry.VerifiedTransferStructOutput[]],
    "view"
  >;

  getTransfersPaginated: TypedContractMethod<
    [borrower: AddressLike, offset: BigNumberish, limit: BigNumberish],
    [IRemittanceCreditRegistry.VerifiedTransferStructOutput[]],
    "view"
  >;

  isTransferRecorded: TypedContractMethod<
    [sourceTxHash: BytesLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  recordVerifiedTransfer: TypedContractMethod<
    [
      borrower: AddressLike,
      sender: AddressLike,
      amount: BigNumberish,
      sourceTimestamp: BigNumberish,
      sourceTxHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  recorder: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setRecorder: TypedContractMethod<
    [newRecorder: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getStats"
  ): TypedContractMethod<
    [borrower: AddressLike, lookbackWindowSeconds: BigNumberish],
    [IRemittanceCreditRegistry.RemittanceStatsStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTransfers"
  ): TypedContractMethod<
    [borrower: AddressLike],
    [IRemittanceCreditRegistry.VerifiedTransferStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTransfersPaginated"
  ): TypedContractMethod<
    [borrower: AddressLike, offset: BigNumberish, limit: BigNumberish],
    [IRemittanceCreditRegistry.VerifiedTransferStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "isTransferRecorded"
  ): TypedContractMethod<[sourceTxHash: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordVerifiedTransfer"
  ): TypedContractMethod<
    [
      borrower: AddressLike,
      sender: AddressLike,
      amount: BigNumberish,
      sourceTimestamp: BigNumberish,
      sourceTxHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recorder"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRecorder"
  ): TypedContractMethod<[newRecorder: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RecorderUpdated"
  ): TypedContractEvent<
    RecorderUpdatedEvent.InputTuple,
    RecorderUpdatedEvent.OutputTuple,
    RecorderUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "VerifiedTransferRecorded"
  ): TypedContractEvent<
    VerifiedTransferRecordedEvent.InputTuple,
    VerifiedTransferRecordedEvent.OutputTuple,
    VerifiedTransferRecordedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RecorderUpdated(address,address)": TypedContractEvent<
      RecorderUpdatedEvent.InputTuple,
      RecorderUpdatedEvent.OutputTuple,
      RecorderUpdatedEvent.OutputObject
    >;
    RecorderUpdated: TypedContractEvent<
      RecorderUpdatedEvent.InputTuple,
      RecorderUpdatedEvent.OutputTuple,
      RecorderUpdatedEvent.OutputObject
    >;

    "VerifiedTransferRecorded(address,address,uint256,uint64,bytes32)": TypedContractEvent<
      VerifiedTransferRecordedEvent.InputTuple,
      VerifiedTransferRecordedEvent.OutputTuple,
      VerifiedTransferRecordedEvent.OutputObject
    >;
    VerifiedTransferRecorded: TypedContractEvent<
      VerifiedTransferRecordedEvent.InputTuple,
      VerifiedTransferRecordedEvent.OutputTuple,
      VerifiedTransferRecordedEvent.OutputObject
    >;
  };
}
