/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace RemittanceMicroLoan {
  export type BorrowerStruct = {
    registered: boolean;
    declaredSender: AddressLike;
    eligible: boolean;
    creditLimit: BigNumberish;
    riskScoreBps: BigNumberish;
    outstandingPrincipal: BigNumberish;
    lastReviewedAt: BigNumberish;
  };

  export type BorrowerStructOutput = [
    registered: boolean,
    declaredSender: string,
    eligible: boolean,
    creditLimit: bigint,
    riskScoreBps: bigint,
    outstandingPrincipal: bigint,
    lastReviewedAt: bigint
  ] & {
    registered: boolean;
    declaredSender: string;
    eligible: boolean;
    creditLimit: bigint;
    riskScoreBps: bigint;
    outstandingPrincipal: bigint;
    lastReviewedAt: bigint;
  };
}

export interface RemittanceMicroLoanInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "availableCredit"
      | "borrowers"
      | "creditEngine"
      | "fundPool"
      | "getBorrower"
      | "loanToken"
      | "owner"
      | "pause"
      | "paused"
      | "precompile"
      | "registerBorrower"
      | "registry"
      | "renounceOwnership"
      | "repay"
      | "requestCreditReview"
      | "requestLoan"
      | "setCreditEngine"
      | "setLoanToken"
      | "setPrecompile"
      | "setRegistry"
      | "submitRemittanceProof"
      | "submitRemittanceProofBatch"
      | "transferOwnership"
      | "unpause"
      | "withdrawPool"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BorrowerRegistered"
      | "CreditEngineUpdated"
      | "CreditReviewed"
      | "LoanDisbursed"
      | "LoanRepaid"
      | "LoanTokenUpdated"
      | "OwnershipTransferred"
      | "Paused"
      | "PoolFunded"
      | "PoolWithdrawn"
      | "PrecompileUpdated"
      | "RegistryUpdated"
      | "RemittanceVerified"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "availableCredit",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "borrowers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "creditEngine",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fundPool",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBorrower",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "loanToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "precompile",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerBorrower",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "repay", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "requestCreditReview",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestLoan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setCreditEngine",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setLoanToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPrecompile",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitRemittanceProof",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike,
      BytesLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "submitRemittanceProofBatch",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish[],
      BytesLike[],
      BytesLike[],
      BytesLike,
      AddressLike[],
      BigNumberish[],
      BigNumberish[],
      BytesLike[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawPool",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "availableCredit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "borrowers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "creditEngine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fundPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBorrower",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "loanToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "precompile", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerBorrower",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "repay", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestCreditReview",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestLoan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCreditEngine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLoanToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPrecompile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitRemittanceProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitRemittanceProofBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawPool",
    data: BytesLike
  ): Result;
}

export namespace BorrowerRegisteredEvent {
  export type InputTuple = [borrower: AddressLike, declaredSender: AddressLike];
  export type OutputTuple = [borrower: string, declaredSender: string];
  export interface OutputObject {
    borrower: string;
    declaredSender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CreditEngineUpdatedEvent {
  export type InputTuple = [newCreditEngine: AddressLike];
  export type OutputTuple = [newCreditEngine: string];
  export interface OutputObject {
    newCreditEngine: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CreditReviewedEvent {
  export type InputTuple = [
    borrower: AddressLike,
    eligible: boolean,
    creditLimit: BigNumberish,
    riskScoreBps: BigNumberish,
    rationale: string
  ];
  export type OutputTuple = [
    borrower: string,
    eligible: boolean,
    creditLimit: bigint,
    riskScoreBps: bigint,
    rationale: string
  ];
  export interface OutputObject {
    borrower: string;
    eligible: boolean;
    creditLimit: bigint;
    riskScoreBps: bigint;
    rationale: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanDisbursedEvent {
  export type InputTuple = [
    borrower: AddressLike,
    amount: BigNumberish,
    newOutstanding: BigNumberish
  ];
  export type OutputTuple = [
    borrower: string,
    amount: bigint,
    newOutstanding: bigint
  ];
  export interface OutputObject {
    borrower: string;
    amount: bigint;
    newOutstanding: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanRepaidEvent {
  export type InputTuple = [
    borrower: AddressLike,
    amount: BigNumberish,
    newOutstanding: BigNumberish
  ];
  export type OutputTuple = [
    borrower: string,
    amount: bigint,
    newOutstanding: bigint
  ];
  export interface OutputObject {
    borrower: string;
    amount: bigint;
    newOutstanding: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanTokenUpdatedEvent {
  export type InputTuple = [newLoanToken: AddressLike];
  export type OutputTuple = [newLoanToken: string];
  export interface OutputObject {
    newLoanToken: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolFundedEvent {
  export type InputTuple = [funder: AddressLike, amount: BigNumberish];
  export type OutputTuple = [funder: string, amount: bigint];
  export interface OutputObject {
    funder: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolWithdrawnEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PrecompileUpdatedEvent {
  export type InputTuple = [newPrecompile: AddressLike];
  export type OutputTuple = [newPrecompile: string];
  export interface OutputObject {
    newPrecompile: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RegistryUpdatedEvent {
  export type InputTuple = [newRegistry: AddressLike];
  export type OutputTuple = [newRegistry: string];
  export interface OutputObject {
    newRegistry: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RemittanceVerifiedEvent {
  export type InputTuple = [
    borrower: AddressLike,
    sender: AddressLike,
    amount: BigNumberish,
    sourceTimestamp: BigNumberish,
    sourceTxHash: BytesLike
  ];
  export type OutputTuple = [
    borrower: string,
    sender: string,
    amount: bigint,
    sourceTimestamp: bigint,
    sourceTxHash: string
  ];
  export interface OutputObject {
    borrower: string;
    sender: string;
    amount: bigint;
    sourceTimestamp: bigint;
    sourceTxHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RemittanceMicroLoan extends BaseContract {
  connect(runner?: ContractRunner | null): RemittanceMicroLoan;
  waitForDeployment(): Promise<this>;

  interface: RemittanceMicroLoanInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  availableCredit: TypedContractMethod<
    [borrower: AddressLike],
    [bigint],
    "view"
  >;

  borrowers: TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, string, boolean, bigint, bigint, bigint, bigint] & {
        registered: boolean;
        declaredSender: string;
        eligible: boolean;
        creditLimit: bigint;
        riskScoreBps: bigint;
        outstandingPrincipal: bigint;
        lastReviewedAt: bigint;
      }
    ],
    "view"
  >;

  creditEngine: TypedContractMethod<[], [string], "view">;

  fundPool: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getBorrower: TypedContractMethod<
    [borrower: AddressLike],
    [RemittanceMicroLoan.BorrowerStructOutput],
    "view"
  >;

  loanToken: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  precompile: TypedContractMethod<[], [string], "view">;

  registerBorrower: TypedContractMethod<
    [declaredSender: AddressLike],
    [void],
    "nonpayable"
  >;

  registry: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  repay: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  requestCreditReview: TypedContractMethod<
    [borrower: AddressLike],
    [void],
    "nonpayable"
  >;

  requestLoan: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setCreditEngine: TypedContractMethod<
    [_creditEngine: AddressLike],
    [void],
    "nonpayable"
  >;

  setLoanToken: TypedContractMethod<
    [_loanToken: AddressLike],
    [void],
    "nonpayable"
  >;

  setPrecompile: TypedContractMethod<
    [_precompile: AddressLike],
    [void],
    "nonpayable"
  >;

  setRegistry: TypedContractMethod<
    [_registry: AddressLike],
    [void],
    "nonpayable"
  >;

  submitRemittanceProof: TypedContractMethod<
    [
      borrower: AddressLike,
      chainKey: BigNumberish,
      blockHeight: BigNumberish,
      encodedTx: BytesLike,
      merkleProof: BytesLike,
      continuityProof: BytesLike,
      claimedSender: AddressLike,
      claimedAmount: BigNumberish,
      claimedTimestamp: BigNumberish,
      sourceTxHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  submitRemittanceProofBatch: TypedContractMethod<
    [
      borrower: AddressLike,
      chainKey: BigNumberish,
      blockHeights: BigNumberish[],
      encodedTxs: BytesLike[],
      merkleProofs: BytesLike[],
      continuityProof: BytesLike,
      claimedSenders: AddressLike[],
      claimedAmounts: BigNumberish[],
      claimedTimestamps: BigNumberish[],
      sourceTxHashes: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  withdrawPool: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "availableCredit"
  ): TypedContractMethod<[borrower: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "borrowers"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, string, boolean, bigint, bigint, bigint, bigint] & {
        registered: boolean;
        declaredSender: string;
        eligible: boolean;
        creditLimit: bigint;
        riskScoreBps: bigint;
        outstandingPrincipal: bigint;
        lastReviewedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "creditEngine"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "fundPool"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getBorrower"
  ): TypedContractMethod<
    [borrower: AddressLike],
    [RemittanceMicroLoan.BorrowerStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "loanToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "precompile"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerBorrower"
  ): TypedContractMethod<[declaredSender: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "repay"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestCreditReview"
  ): TypedContractMethod<[borrower: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestLoan"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setCreditEngine"
  ): TypedContractMethod<[_creditEngine: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setLoanToken"
  ): TypedContractMethod<[_loanToken: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPrecompile"
  ): TypedContractMethod<[_precompile: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRegistry"
  ): TypedContractMethod<[_registry: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitRemittanceProof"
  ): TypedContractMethod<
    [
      borrower: AddressLike,
      chainKey: BigNumberish,
      blockHeight: BigNumberish,
      encodedTx: BytesLike,
      merkleProof: BytesLike,
      continuityProof: BytesLike,
      claimedSender: AddressLike,
      claimedAmount: BigNumberish,
      claimedTimestamp: BigNumberish,
      sourceTxHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitRemittanceProofBatch"
  ): TypedContractMethod<
    [
      borrower: AddressLike,
      chainKey: BigNumberish,
      blockHeights: BigNumberish[],
      encodedTxs: BytesLike[],
      merkleProofs: BytesLike[],
      continuityProof: BytesLike,
      claimedSenders: AddressLike[],
      claimedAmounts: BigNumberish[],
      claimedTimestamps: BigNumberish[],
      sourceTxHashes: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawPool"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BorrowerRegistered"
  ): TypedContractEvent<
    BorrowerRegisteredEvent.InputTuple,
    BorrowerRegisteredEvent.OutputTuple,
    BorrowerRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "CreditEngineUpdated"
  ): TypedContractEvent<
    CreditEngineUpdatedEvent.InputTuple,
    CreditEngineUpdatedEvent.OutputTuple,
    CreditEngineUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "CreditReviewed"
  ): TypedContractEvent<
    CreditReviewedEvent.InputTuple,
    CreditReviewedEvent.OutputTuple,
    CreditReviewedEvent.OutputObject
  >;
  getEvent(
    key: "LoanDisbursed"
  ): TypedContractEvent<
    LoanDisbursedEvent.InputTuple,
    LoanDisbursedEvent.OutputTuple,
    LoanDisbursedEvent.OutputObject
  >;
  getEvent(
    key: "LoanRepaid"
  ): TypedContractEvent<
    LoanRepaidEvent.InputTuple,
    LoanRepaidEvent.OutputTuple,
    LoanRepaidEvent.OutputObject
  >;
  getEvent(
    key: "LoanTokenUpdated"
  ): TypedContractEvent<
    LoanTokenUpdatedEvent.InputTuple,
    LoanTokenUpdatedEvent.OutputTuple,
    LoanTokenUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PoolFunded"
  ): TypedContractEvent<
    PoolFundedEvent.InputTuple,
    PoolFundedEvent.OutputTuple,
    PoolFundedEvent.OutputObject
  >;
  getEvent(
    key: "PoolWithdrawn"
  ): TypedContractEvent<
    PoolWithdrawnEvent.InputTuple,
    PoolWithdrawnEvent.OutputTuple,
    PoolWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "PrecompileUpdated"
  ): TypedContractEvent<
    PrecompileUpdatedEvent.InputTuple,
    PrecompileUpdatedEvent.OutputTuple,
    PrecompileUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RegistryUpdated"
  ): TypedContractEvent<
    RegistryUpdatedEvent.InputTuple,
    RegistryUpdatedEvent.OutputTuple,
    RegistryUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RemittanceVerified"
  ): TypedContractEvent<
    RemittanceVerifiedEvent.InputTuple,
    RemittanceVerifiedEvent.OutputTuple,
    RemittanceVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "BorrowerRegistered(address,address)": TypedContractEvent<
      BorrowerRegisteredEvent.InputTuple,
      BorrowerRegisteredEvent.OutputTuple,
      BorrowerRegisteredEvent.OutputObject
    >;
    BorrowerRegistered: TypedContractEvent<
      BorrowerRegisteredEvent.InputTuple,
      BorrowerRegisteredEvent.OutputTuple,
      BorrowerRegisteredEvent.OutputObject
    >;

    "CreditEngineUpdated(address)": TypedContractEvent<
      CreditEngineUpdatedEvent.InputTuple,
      CreditEngineUpdatedEvent.OutputTuple,
      CreditEngineUpdatedEvent.OutputObject
    >;
    CreditEngineUpdated: TypedContractEvent<
      CreditEngineUpdatedEvent.InputTuple,
      CreditEngineUpdatedEvent.OutputTuple,
      CreditEngineUpdatedEvent.OutputObject
    >;

    "CreditReviewed(address,bool,uint256,uint16,string)": TypedContractEvent<
      CreditReviewedEvent.InputTuple,
      CreditReviewedEvent.OutputTuple,
      CreditReviewedEvent.OutputObject
    >;
    CreditReviewed: TypedContractEvent<
      CreditReviewedEvent.InputTuple,
      CreditReviewedEvent.OutputTuple,
      CreditReviewedEvent.OutputObject
    >;

    "LoanDisbursed(address,uint256,uint256)": TypedContractEvent<
      LoanDisbursedEvent.InputTuple,
      LoanDisbursedEvent.OutputTuple,
      LoanDisbursedEvent.OutputObject
    >;
    LoanDisbursed: TypedContractEvent<
      LoanDisbursedEvent.InputTuple,
      LoanDisbursedEvent.OutputTuple,
      LoanDisbursedEvent.OutputObject
    >;

    "LoanRepaid(address,uint256,uint256)": TypedContractEvent<
      LoanRepaidEvent.InputTuple,
      LoanRepaidEvent.OutputTuple,
      LoanRepaidEvent.OutputObject
    >;
    LoanRepaid: TypedContractEvent<
      LoanRepaidEvent.InputTuple,
      LoanRepaidEvent.OutputTuple,
      LoanRepaidEvent.OutputObject
    >;

    "LoanTokenUpdated(address)": TypedContractEvent<
      LoanTokenUpdatedEvent.InputTuple,
      LoanTokenUpdatedEvent.OutputTuple,
      LoanTokenUpdatedEvent.OutputObject
    >;
    LoanTokenUpdated: TypedContractEvent<
      LoanTokenUpdatedEvent.InputTuple,
      LoanTokenUpdatedEvent.OutputTuple,
      LoanTokenUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PoolFunded(address,uint256)": TypedContractEvent<
      PoolFundedEvent.InputTuple,
      PoolFundedEvent.OutputTuple,
      PoolFundedEvent.OutputObject
    >;
    PoolFunded: TypedContractEvent<
      PoolFundedEvent.InputTuple,
      PoolFundedEvent.OutputTuple,
      PoolFundedEvent.OutputObject
    >;

    "PoolWithdrawn(address,uint256)": TypedContractEvent<
      PoolWithdrawnEvent.InputTuple,
      PoolWithdrawnEvent.OutputTuple,
      PoolWithdrawnEvent.OutputObject
    >;
    PoolWithdrawn: TypedContractEvent<
      PoolWithdrawnEvent.InputTuple,
      PoolWithdrawnEvent.OutputTuple,
      PoolWithdrawnEvent.OutputObject
    >;

    "PrecompileUpdated(address)": TypedContractEvent<
      PrecompileUpdatedEvent.InputTuple,
      PrecompileUpdatedEvent.OutputTuple,
      PrecompileUpdatedEvent.OutputObject
    >;
    PrecompileUpdated: TypedContractEvent<
      PrecompileUpdatedEvent.InputTuple,
      PrecompileUpdatedEvent.OutputTuple,
      PrecompileUpdatedEvent.OutputObject
    >;

    "RegistryUpdated(address)": TypedContractEvent<
      RegistryUpdatedEvent.InputTuple,
      RegistryUpdatedEvent.OutputTuple,
      RegistryUpdatedEvent.OutputObject
    >;
    RegistryUpdated: TypedContractEvent<
      RegistryUpdatedEvent.InputTuple,
      RegistryUpdatedEvent.OutputTuple,
      RegistryUpdatedEvent.OutputObject
    >;

    "RemittanceVerified(address,address,uint256,uint64,bytes32)": TypedContractEvent<
      RemittanceVerifiedEvent.InputTuple,
      RemittanceVerifiedEvent.OutputTuple,
      RemittanceVerifiedEvent.OutputObject
    >;
    RemittanceVerified: TypedContractEvent<
      RemittanceVerifiedEvent.InputTuple,
      RemittanceVerifiedEvent.OutputTuple,
      RemittanceVerifiedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
