/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SenderValidationAttestationInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "attest"
      | "getAttestation"
      | "isApproved"
      | "owner"
      | "renounceOwnership"
      | "setWriter"
      | "transferOwnership"
      | "writer"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "SenderAttested"
      | "WriterUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "attest",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getAttestation",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isApproved",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setWriter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "writer", values?: undefined): string;

  decodeFunctionResult(functionFragment: "attest", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAttestation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isApproved", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setWriter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "writer", data: BytesLike): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SenderAttestedEvent {
  export type InputTuple = [
    senderWallet: AddressLike,
    recipient: AddressLike,
    verificationStatus: BigNumberish,
    walletAgeDays: BigNumberish,
    fundingSourceType: BigNumberish,
    riskFlags: BytesLike[],
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    senderWallet: string,
    recipient: string,
    verificationStatus: bigint,
    walletAgeDays: bigint,
    fundingSourceType: bigint,
    riskFlags: string[],
    timestamp: bigint
  ];
  export interface OutputObject {
    senderWallet: string;
    recipient: string;
    verificationStatus: bigint;
    walletAgeDays: bigint;
    fundingSourceType: bigint;
    riskFlags: string[];
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WriterUpdatedEvent {
  export type InputTuple = [
    previousWriter: AddressLike,
    newWriter: AddressLike
  ];
  export type OutputTuple = [previousWriter: string, newWriter: string];
  export interface OutputObject {
    previousWriter: string;
    newWriter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SenderValidationAttestation extends BaseContract {
  connect(runner?: ContractRunner | null): SenderValidationAttestation;
  waitForDeployment(): Promise<this>;

  interface: SenderValidationAttestationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  attest: TypedContractMethod<
    [
      senderWallet: AddressLike,
      recipient: AddressLike,
      verificationStatus: BigNumberish,
      walletAgeDays: BigNumberish,
      fundingSourceType: BigNumberish,
      riskFlags: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  getAttestation: TypedContractMethod<
    [senderWallet: AddressLike, recipient: AddressLike],
    [
      [string, string, bigint, bigint, bigint, string[], bigint, boolean] & {
        sender: string;
        recip: string;
        verificationStatus: bigint;
        walletAgeDays: bigint;
        fundingSourceType: bigint;
        riskFlags: string[];
        timestamp: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  isApproved: TypedContractMethod<
    [senderWallet: AddressLike, recipient: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setWriter: TypedContractMethod<
    [newWriter: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  writer: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "attest"
  ): TypedContractMethod<
    [
      senderWallet: AddressLike,
      recipient: AddressLike,
      verificationStatus: BigNumberish,
      walletAgeDays: BigNumberish,
      fundingSourceType: BigNumberish,
      riskFlags: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAttestation"
  ): TypedContractMethod<
    [senderWallet: AddressLike, recipient: AddressLike],
    [
      [string, string, bigint, bigint, bigint, string[], bigint, boolean] & {
        sender: string;
        recip: string;
        verificationStatus: bigint;
        walletAgeDays: bigint;
        fundingSourceType: bigint;
        riskFlags: string[];
        timestamp: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isApproved"
  ): TypedContractMethod<
    [senderWallet: AddressLike, recipient: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setWriter"
  ): TypedContractMethod<[newWriter: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "writer"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SenderAttested"
  ): TypedContractEvent<
    SenderAttestedEvent.InputTuple,
    SenderAttestedEvent.OutputTuple,
    SenderAttestedEvent.OutputObject
  >;
  getEvent(
    key: "WriterUpdated"
  ): TypedContractEvent<
    WriterUpdatedEvent.InputTuple,
    WriterUpdatedEvent.OutputTuple,
    WriterUpdatedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SenderAttested(address,address,uint8,uint32,uint8,bytes32[],uint64)": TypedContractEvent<
      SenderAttestedEvent.InputTuple,
      SenderAttestedEvent.OutputTuple,
      SenderAttestedEvent.OutputObject
    >;
    SenderAttested: TypedContractEvent<
      SenderAttestedEvent.InputTuple,
      SenderAttestedEvent.OutputTuple,
      SenderAttestedEvent.OutputObject
    >;

    "WriterUpdated(address,address)": TypedContractEvent<
      WriterUpdatedEvent.InputTuple,
      WriterUpdatedEvent.OutputTuple,
      WriterUpdatedEvent.OutputObject
    >;
    WriterUpdated: TypedContractEvent<
      WriterUpdatedEvent.InputTuple,
      WriterUpdatedEvent.OutputTuple,
      WriterUpdatedEvent.OutputObject
    >;
  };
}
