/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace IAttestcoinBlockProver {
  export type MerkleProofEntryStruct = { hash: BytesLike; isLeft: boolean };

  export type MerkleProofEntryStructOutput = [hash: string, isLeft: boolean] & {
    hash: string;
    isLeft: boolean;
  };

  export type MerkleProofStruct = {
    root: BytesLike;
    siblings: IAttestcoinBlockProver.MerkleProofEntryStruct[];
  };

  export type MerkleProofStructOutput = [
    root: string,
    siblings: IAttestcoinBlockProver.MerkleProofEntryStructOutput[]
  ] & {
    root: string;
    siblings: IAttestcoinBlockProver.MerkleProofEntryStructOutput[];
  };

  export type ContinuityProofStruct = {
    lowerEndpointDigest: BytesLike;
    roots: BytesLike[];
  };

  export type ContinuityProofStructOutput = [
    lowerEndpointDigest: string,
    roots: string[]
  ] & { lowerEndpointDigest: string; roots: string[] };
}

export interface VerifyRelayInterface extends Interface {
  getFunction(nameOrSignature: "relayVerifyAndEmit"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "relayVerifyAndEmit",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BytesLike,
      IAttestcoinBlockProver.MerkleProofStruct,
      IAttestcoinBlockProver.ContinuityProofStruct
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "relayVerifyAndEmit",
    data: BytesLike
  ): Result;
}

export interface VerifyRelay extends BaseContract {
  connect(runner?: ContractRunner | null): VerifyRelay;
  waitForDeployment(): Promise<this>;

  interface: VerifyRelayInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  relayVerifyAndEmit: TypedContractMethod<
    [
      precompile: AddressLike,
      chainKey: BigNumberish,
      height: BigNumberish,
      encodedTx: BytesLike,
      merkleProof: IAttestcoinBlockProver.MerkleProofStruct,
      continuityProof: IAttestcoinBlockProver.ContinuityProofStruct
    ],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "relayVerifyAndEmit"
  ): TypedContractMethod<
    [
      precompile: AddressLike,
      chainKey: BigNumberish,
      height: BigNumberish,
      encodedTx: BytesLike,
      merkleProof: IAttestcoinBlockProver.MerkleProofStruct,
      continuityProof: IAttestcoinBlockProver.ContinuityProofStruct
    ],
    [boolean],
    "nonpayable"
  >;

  filters: {};
}
