/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IAttestcoinBlockProver {
  export type MerkleProofEntryStruct = { hash: BytesLike; isLeft: boolean };

  export type MerkleProofEntryStructOutput = [hash: string, isLeft: boolean] & {
    hash: string;
    isLeft: boolean;
  };

  export type MerkleProofStruct = {
    root: BytesLike;
    siblings: IAttestcoinBlockProver.MerkleProofEntryStruct[];
  };

  export type MerkleProofStructOutput = [
    root: string,
    siblings: IAttestcoinBlockProver.MerkleProofEntryStructOutput[]
  ] & {
    root: string;
    siblings: IAttestcoinBlockProver.MerkleProofEntryStructOutput[];
  };

  export type ContinuityProofStruct = {
    lowerEndpointDigest: BytesLike;
    roots: BytesLike[];
  };

  export type ContinuityProofStructOutput = [
    lowerEndpointDigest: string,
    roots: string[]
  ] & { lowerEndpointDigest: string; roots: string[] };
}

export interface IAttestcoinBlockProverInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "verify(uint64,uint64[],bytes[],(bytes32,(bytes32,bool)[])[],(bytes32,bytes32[]))"
      | "verify(uint64,uint64,bytes,(bytes32,(bytes32,bool)[]),(bytes32,bytes32[]))"
      | "verifyAndEmit(uint64,uint64,bytes,(bytes32,(bytes32,bool)[]),(bytes32,bytes32[]))"
      | "verifyAndEmit(uint64,uint64[],bytes[],(bytes32,(bytes32,bool)[])[],(bytes32,bytes32[]))"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "TransactionVerified"): EventFragment;

  encodeFunctionData(
    functionFragment: "verify(uint64,uint64[],bytes[],(bytes32,(bytes32,bool)[])[],(bytes32,bytes32[]))",
    values: [
      BigNumberish,
      BigNumberish[],
      BytesLike[],
      IAttestcoinBlockProver.MerkleProofStruct[],
      IAttestcoinBlockProver.ContinuityProofStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "verify(uint64,uint64,bytes,(bytes32,(bytes32,bool)[]),(bytes32,bytes32[]))",
    values: [
      BigNumberish,
      BigNumberish,
      BytesLike,
      IAttestcoinBlockProver.MerkleProofStruct,
      IAttestcoinBlockProver.ContinuityProofStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyAndEmit(uint64,uint64,bytes,(bytes32,(bytes32,bool)[]),(bytes32,bytes32[]))",
    values: [
      BigNumberish,
      BigNumberish,
      BytesLike,
      IAttestcoinBlockProver.MerkleProofStruct,
      IAttestcoinBlockProver.ContinuityProofStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyAndEmit(uint64,uint64[],bytes[],(bytes32,(bytes32,bool)[])[],(bytes32,bytes32[]))",
    values: [
      BigNumberish,
      BigNumberish[],
      BytesLike[],
      IAttestcoinBlockProver.MerkleProofStruct[],
      IAttestcoinBlockProver.ContinuityProofStruct
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "verify(uint64,uint64[],bytes[],(bytes32,(bytes32,bool)[])[],(bytes32,bytes32[]))",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verify(uint64,uint64,bytes,(bytes32,(bytes32,bool)[]),(bytes32,bytes32[]))",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyAndEmit(uint64,uint64,bytes,(bytes32,(bytes32,bool)[]),(bytes32,bytes32[]))",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyAndEmit(uint64,uint64[],bytes[],(bytes32,(bytes32,bool)[])[],(bytes32,bytes32[]))",
    data: BytesLike
  ): Result;
}

export namespace TransactionVerifiedEvent {
  export type InputTuple = [
    chainKey: BigNumberish,
    height: BigNumberish,
    transactionIndex: BigNumberish
  ];
  export type OutputTuple = [
    chainKey: bigint,
    height: bigint,
    transactionIndex: bigint
  ];
  export interface OutputObject {
    chainKey: bigint;
    height: bigint;
    transactionIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IAttestcoinBlockProver extends BaseContract {
  connect(runner?: ContractRunner | null): IAttestcoinBlockProver;
  waitForDeployment(): Promise<this>;

  interface: IAttestcoinBlockProverInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  "verify(uint64,uint64[],bytes[],(bytes32,(bytes32,bool)[])[],(bytes32,bytes32[]))": TypedContractMethod<
    [
      chainKey: BigNumberish,
      heights: BigNumberish[],
      encodedTransactions: BytesLike[],
      merkleProofs: IAttestcoinBlockProver.MerkleProofStruct[],
      sharedContinuityProof: IAttestcoinBlockProver.ContinuityProofStruct
    ],
    [boolean],
    "view"
  >;

  "verify(uint64,uint64,bytes,(bytes32,(bytes32,bool)[]),(bytes32,bytes32[]))": TypedContractMethod<
    [
      chainKey: BigNumberish,
      height: BigNumberish,
      encodedTransaction: BytesLike,
      merkleProof: IAttestcoinBlockProver.MerkleProofStruct,
      continuityProof: IAttestcoinBlockProver.ContinuityProofStruct
    ],
    [boolean],
    "view"
  >;

  "verifyAndEmit(uint64,uint64,bytes,(bytes32,(bytes32,bool)[]),(bytes32,bytes32[]))": TypedContractMethod<
    [
      chainKey: BigNumberish,
      height: BigNumberish,
      encodedTransaction: BytesLike,
      merkleProof: IAttestcoinBlockProver.MerkleProofStruct,
      continuityProof: IAttestcoinBlockProver.ContinuityProofStruct
    ],
    [boolean],
    "nonpayable"
  >;

  "verifyAndEmit(uint64,uint64[],bytes[],(bytes32,(bytes32,bool)[])[],(bytes32,bytes32[]))": TypedContractMethod<
    [
      chainKey: BigNumberish,
      heights: BigNumberish[],
      encodedTransactions: BytesLike[],
      merkleProofs: IAttestcoinBlockProver.MerkleProofStruct[],
      sharedContinuityProof: IAttestcoinBlockProver.ContinuityProofStruct
    ],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "verify(uint64,uint64[],bytes[],(bytes32,(bytes32,bool)[])[],(bytes32,bytes32[]))"
  ): TypedContractMethod<
    [
      chainKey: BigNumberish,
      heights: BigNumberish[],
      encodedTransactions: BytesLike[],
      merkleProofs: IAttestcoinBlockProver.MerkleProofStruct[],
      sharedContinuityProof: IAttestcoinBlockProver.ContinuityProofStruct
    ],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "verify(uint64,uint64,bytes,(bytes32,(bytes32,bool)[]),(bytes32,bytes32[]))"
  ): TypedContractMethod<
    [
      chainKey: BigNumberish,
      height: BigNumberish,
      encodedTransaction: BytesLike,
      merkleProof: IAttestcoinBlockProver.MerkleProofStruct,
      continuityProof: IAttestcoinBlockProver.ContinuityProofStruct
    ],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifyAndEmit(uint64,uint64,bytes,(bytes32,(bytes32,bool)[]),(bytes32,bytes32[]))"
  ): TypedContractMethod<
    [
      chainKey: BigNumberish,
      height: BigNumberish,
      encodedTransaction: BytesLike,
      merkleProof: IAttestcoinBlockProver.MerkleProofStruct,
      continuityProof: IAttestcoinBlockProver.ContinuityProofStruct
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyAndEmit(uint64,uint64[],bytes[],(bytes32,(bytes32,bool)[])[],(bytes32,bytes32[]))"
  ): TypedContractMethod<
    [
      chainKey: BigNumberish,
      heights: BigNumberish[],
      encodedTransactions: BytesLike[],
      merkleProofs: IAttestcoinBlockProver.MerkleProofStruct[],
      sharedContinuityProof: IAttestcoinBlockProver.ContinuityProofStruct
    ],
    [boolean],
    "nonpayable"
  >;

  getEvent(
    key: "TransactionVerified"
  ): TypedContractEvent<
    TransactionVerifiedEvent.InputTuple,
    TransactionVerifiedEvent.OutputTuple,
    TransactionVerifiedEvent.OutputObject
  >;

  filters: {
    "TransactionVerified(uint64,uint64,uint64)": TypedContractEvent<
      TransactionVerifiedEvent.InputTuple,
      TransactionVerifiedEvent.OutputTuple,
      TransactionVerifiedEvent.OutputObject
    >;
    TransactionVerified: TypedContractEvent<
      TransactionVerifiedEvent.InputTuple,
      TransactionVerifiedEvent.OutputTuple,
      TransactionVerifiedEvent.OutputObject
    >;
  };
}
