/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IAttestcoinBlockProverInterface extends Interface {
  getFunction(nameOrSignature: "verify" | "verifyBatch"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "verify",
    values: [BigNumberish, BigNumberish, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyBatch",
    values: [BigNumberish, BigNumberish[], BytesLike[], BytesLike[], BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyBatch",
    data: BytesLike
  ): Result;
}

export interface IAttestcoinBlockProver extends BaseContract {
  connect(runner?: ContractRunner | null): IAttestcoinBlockProver;
  waitForDeployment(): Promise<this>;

  interface: IAttestcoinBlockProverInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  verify: TypedContractMethod<
    [
      chainKey: BigNumberish,
      blockHeight: BigNumberish,
      encodedTx: BytesLike,
      merkleProof: BytesLike,
      continuityProof: BytesLike
    ],
    [boolean],
    "view"
  >;

  verifyBatch: TypedContractMethod<
    [
      chainKey: BigNumberish,
      blockHeights: BigNumberish[],
      encodedTxs: BytesLike[],
      merkleProofs: BytesLike[],
      continuityProof: BytesLike
    ],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "verify"
  ): TypedContractMethod<
    [
      chainKey: BigNumberish,
      blockHeight: BigNumberish,
      encodedTx: BytesLike,
      merkleProof: BytesLike,
      continuityProof: BytesLike
    ],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifyBatch"
  ): TypedContractMethod<
    [
      chainKey: BigNumberish,
      blockHeights: BigNumberish[],
      encodedTxs: BytesLike[],
      merkleProofs: BytesLike[],
      continuityProof: BytesLike
    ],
    [boolean],
    "view"
  >;

  filters: {};
}
