/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAttestcoinBlockProver } from "./IAttestcoinBlockProver";
export type { IRemittanceCreditRegistry } from "./IRemittanceCreditRegistry";
