/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IRemittanceCreditRegistry {
  export type RemittanceStatsStruct = {
    transferCount: BigNumberish;
    totalAmount: BigNumberish;
    firstTimestamp: BigNumberish;
    lastTimestamp: BigNumberish;
    avgIntervalSeconds: BigNumberish;
    intervalConsistencyBps: BigNumberish;
  };

  export type RemittanceStatsStructOutput = [
    transferCount: bigint,
    totalAmount: bigint,
    firstTimestamp: bigint,
    lastTimestamp: bigint,
    avgIntervalSeconds: bigint,
    intervalConsistencyBps: bigint
  ] & {
    transferCount: bigint;
    totalAmount: bigint;
    firstTimestamp: bigint;
    lastTimestamp: bigint;
    avgIntervalSeconds: bigint;
    intervalConsistencyBps: bigint;
  };

  export type VerifiedTransferStruct = {
    sender: AddressLike;
    amount: BigNumberish;
    sourceTimestamp: BigNumberish;
    sourceTxHash: BytesLike;
    recordedAt: BigNumberish;
  };

  export type VerifiedTransferStructOutput = [
    sender: string,
    amount: bigint,
    sourceTimestamp: bigint,
    sourceTxHash: string,
    recordedAt: bigint
  ] & {
    sender: string;
    amount: bigint;
    sourceTimestamp: bigint;
    sourceTxHash: string;
    recordedAt: bigint;
  };
}

export interface IRemittanceCreditRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getStats"
      | "getTransfers"
      | "isTransferRecorded"
      | "recordVerifiedTransfer"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getStats",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTransfers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isTransferRecorded",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordVerifiedTransfer",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "getStats", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTransfers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTransferRecorded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordVerifiedTransfer",
    data: BytesLike
  ): Result;
}

export interface IRemittanceCreditRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IRemittanceCreditRegistry;
  waitForDeployment(): Promise<this>;

  interface: IRemittanceCreditRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getStats: TypedContractMethod<
    [borrower: AddressLike, lookbackWindowSeconds: BigNumberish],
    [IRemittanceCreditRegistry.RemittanceStatsStructOutput],
    "view"
  >;

  getTransfers: TypedContractMethod<
    [borrower: AddressLike],
    [IRemittanceCreditRegistry.VerifiedTransferStructOutput[]],
    "view"
  >;

  isTransferRecorded: TypedContractMethod<
    [sourceTxHash: BytesLike],
    [boolean],
    "view"
  >;

  recordVerifiedTransfer: TypedContractMethod<
    [
      borrower: AddressLike,
      sender: AddressLike,
      amount: BigNumberish,
      sourceTimestamp: BigNumberish,
      sourceTxHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getStats"
  ): TypedContractMethod<
    [borrower: AddressLike, lookbackWindowSeconds: BigNumberish],
    [IRemittanceCreditRegistry.RemittanceStatsStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTransfers"
  ): TypedContractMethod<
    [borrower: AddressLike],
    [IRemittanceCreditRegistry.VerifiedTransferStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "isTransferRecorded"
  ): TypedContractMethod<[sourceTxHash: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "recordVerifiedTransfer"
  ): TypedContractMethod<
    [
      borrower: AddressLike,
      sender: AddressLike,
      amount: BigNumberish,
      sourceTimestamp: BigNumberish,
      sourceTxHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
