/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  VerifyRelay,
  VerifyRelayInterface,
} from "../../contracts/VerifyRelay";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "precompile",
        type: "address",
      },
      {
        internalType: "uint64",
        name: "chainKey",
        type: "uint64",
      },
      {
        internalType: "uint64",
        name: "height",
        type: "uint64",
      },
      {
        internalType: "bytes",
        name: "encodedTx",
        type: "bytes",
      },
      {
        components: [
          {
            internalType: "bytes32",
            name: "root",
            type: "bytes32",
          },
          {
            components: [
              {
                internalType: "bytes32",
                name: "hash",
                type: "bytes32",
              },
              {
                internalType: "bool",
                name: "isLeft",
                type: "bool",
              },
            ],
            internalType: "struct IAttestcoinBlockProver.MerkleProofEntry[]",
            name: "siblings",
            type: "tuple[]",
          },
        ],
        internalType: "struct IAttestcoinBlockProver.MerkleProof",
        name: "merkleProof",
        type: "tuple",
      },
      {
        components: [
          {
            internalType: "bytes32",
            name: "lowerEndpointDigest",
            type: "bytes32",
          },
          {
            internalType: "bytes32[]",
            name: "roots",
            type: "bytes32[]",
          },
        ],
        internalType: "struct IAttestcoinBlockProver.ContinuityProof",
        name: "continuityProof",
        type: "tuple",
      },
    ],
    name: "relayVerifyAndEmit",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608080604052346100165761030b908161001c8239f35b600080fdfe608060408181526004908136101561001657600080fd5b6000803560e01c63a43f5e551461002c57600080fd5b34610258576003199360c03686011261025b5783356001600160a01b03811695908690036102d15760249586359167ffffffffffffffff928381168091036102cd57604435918483168093036102c95760643590858211610286573660238301121561028657818a013586811161028257368c828501011161028257608435908782116102c557813603938b848601126102c15760a435968988116102bd57873603968d868901126102b957928e9f8f938260a48f601f9f9e9c9a98968397869f9d9b996302f4d16760e01b84528301528582015260a0604482015201520160c48d01378b60c4828d0101528919998a9101168a019060c08b83030160648c01528061010483019f013560c4830152878101356022198095018112156102b957018088019e908e013591908983116102b9578f8360061b3603126102b9579082610124928f60e484015252019d908b5b81811061028a57505050888d03016084890152828b01358c5284830135910181121561028657019882898b01359a0190848b11610286578a60051b9182360381136102825760208281018b9052828b018d90529b6001600160fb1b03106102825788606089858f97958297839685830137010301925af196871561027857859761020c575b888888519015158152f35b909192939495965087933d8911610270575b601f85011685019283118584101761025f5750508591839186528101031261025b5751908115158203610258575090388080808080610201565b80fd5b5080fd5b634e487b7160e01b86526041905284fd5b3d945061021e565b86513d87823e3d90fd5b8880fd5b8780fd5b90919e8f80358252602080910135908115158092036102b5578201528d019e8d01919060010161017c565b8e80fd5b8c80fd5b8b80fd5b8a80fd5b8980fd5b8680fd5b8580fd5b8280fdfea2646970667358221220ad54eb0576cc81c41a054fd058fd2b1b8ce51db8ea263ed5b267d1d5fbff590764736f6c63430008180033";

type VerifyRelayConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: VerifyRelayConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class VerifyRelay__factory extends ContractFactory {
  constructor(...args: VerifyRelayConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      VerifyRelay & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): VerifyRelay__factory {
    return super.connect(runner) as VerifyRelay__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): VerifyRelayInterface {
    return new Interface(_abi) as VerifyRelayInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): VerifyRelay {
    return new Contract(address, _abi, runner) as unknown as VerifyRelay;
  }
}
