/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAttestcoinBlockProver,
  IAttestcoinBlockProverInterface,
} from "../../../contracts/interfaces/IAttestcoinBlockProver";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint32",
        name: "chainKey",
        type: "uint32",
      },
      {
        internalType: "uint64",
        name: "blockHeight",
        type: "uint64",
      },
      {
        internalType: "bytes",
        name: "encodedTx",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "merkleProof",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "continuityProof",
        type: "bytes",
      },
    ],
    name: "verify",
    outputs: [
      {
        internalType: "bool",
        name: "verified",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "chainKey",
        type: "uint32",
      },
      {
        internalType: "uint64[]",
        name: "blockHeights",
        type: "uint64[]",
      },
      {
        internalType: "bytes[]",
        name: "encodedTxs",
        type: "bytes[]",
      },
      {
        internalType: "bytes[]",
        name: "merkleProofs",
        type: "bytes[]",
      },
      {
        internalType: "bytes",
        name: "continuityProof",
        type: "bytes",
      },
    ],
    name: "verifyBatch",
    outputs: [
      {
        internalType: "bool",
        name: "verified",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IAttestcoinBlockProver__factory {
  static readonly abi = _abi;
  static createInterface(): IAttestcoinBlockProverInterface {
    return new Interface(_abi) as IAttestcoinBlockProverInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAttestcoinBlockProver {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IAttestcoinBlockProver;
  }
}
