/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAttestcoinBlockProver,
  IAttestcoinBlockProverInterface,
} from "../../../contracts/interfaces/IAttestcoinBlockProver";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint64",
        name: "chainKey",
        type: "uint64",
      },
      {
        indexed: true,
        internalType: "uint64",
        name: "height",
        type: "uint64",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "transactionIndex",
        type: "uint64",
      },
    ],
    name: "TransactionVerified",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint64",
        name: "chainKey",
        type: "uint64",
      },
      {
        internalType: "uint64[]",
        name: "heights",
        type: "uint64[]",
      },
      {
        internalType: "bytes[]",
        name: "encodedTransactions",
        type: "bytes[]",
      },
      {
        components: [
          {
            internalType: "bytes32",
            name: "root",
            type: "bytes32",
          },
          {
            components: [
              {
                internalType: "bytes32",
                name: "hash",
                type: "bytes32",
              },
              {
                internalType: "bool",
                name: "isLeft",
                type: "bool",
              },
            ],
            internalType: "struct IAttestcoinBlockProver.MerkleProofEntry[]",
            name: "siblings",
            type: "tuple[]",
          },
        ],
        internalType: "struct IAttestcoinBlockProver.MerkleProof[]",
        name: "merkleProofs",
        type: "tuple[]",
      },
      {
        components: [
          {
            internalType: "bytes32",
            name: "lowerEndpointDigest",
            type: "bytes32",
          },
          {
            internalType: "bytes32[]",
            name: "roots",
            type: "bytes32[]",
          },
        ],
        internalType: "struct IAttestcoinBlockProver.ContinuityProof",
        name: "sharedContinuityProof",
        type: "tuple",
      },
    ],
    name: "verify",
    outputs: [
      {
        internalType: "bool",
        name: "verified",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint64",
        name: "chainKey",
        type: "uint64",
      },
      {
        internalType: "uint64",
        name: "height",
        type: "uint64",
      },
      {
        internalType: "bytes",
        name: "encodedTransaction",
        type: "bytes",
      },
      {
        components: [
          {
            internalType: "bytes32",
            name: "root",
            type: "bytes32",
          },
          {
            components: [
              {
                internalType: "bytes32",
                name: "hash",
                type: "bytes32",
              },
              {
                internalType: "bool",
                name: "isLeft",
                type: "bool",
              },
            ],
            internalType: "struct IAttestcoinBlockProver.MerkleProofEntry[]",
            name: "siblings",
            type: "tuple[]",
          },
        ],
        internalType: "struct IAttestcoinBlockProver.MerkleProof",
        name: "merkleProof",
        type: "tuple",
      },
      {
        components: [
          {
            internalType: "bytes32",
            name: "lowerEndpointDigest",
            type: "bytes32",
          },
          {
            internalType: "bytes32[]",
            name: "roots",
            type: "bytes32[]",
          },
        ],
        internalType: "struct IAttestcoinBlockProver.ContinuityProof",
        name: "continuityProof",
        type: "tuple",
      },
    ],
    name: "verify",
    outputs: [
      {
        internalType: "bool",
        name: "verified",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint64",
        name: "chainKey",
        type: "uint64",
      },
      {
        internalType: "uint64",
        name: "height",
        type: "uint64",
      },
      {
        internalType: "bytes",
        name: "encodedTransaction",
        type: "bytes",
      },
      {
        components: [
          {
            internalType: "bytes32",
            name: "root",
            type: "bytes32",
          },
          {
            components: [
              {
                internalType: "bytes32",
                name: "hash",
                type: "bytes32",
              },
              {
                internalType: "bool",
                name: "isLeft",
                type: "bool",
              },
            ],
            internalType: "struct IAttestcoinBlockProver.MerkleProofEntry[]",
            name: "siblings",
            type: "tuple[]",
          },
        ],
        internalType: "struct IAttestcoinBlockProver.MerkleProof",
        name: "merkleProof",
        type: "tuple",
      },
      {
        components: [
          {
            internalType: "bytes32",
            name: "lowerEndpointDigest",
            type: "bytes32",
          },
          {
            internalType: "bytes32[]",
            name: "roots",
            type: "bytes32[]",
          },
        ],
        internalType: "struct IAttestcoinBlockProver.ContinuityProof",
        name: "continuityProof",
        type: "tuple",
      },
    ],
    name: "verifyAndEmit",
    outputs: [
      {
        internalType: "bool",
        name: "verified",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint64",
        name: "chainKey",
        type: "uint64",
      },
      {
        internalType: "uint64[]",
        name: "heights",
        type: "uint64[]",
      },
      {
        internalType: "bytes[]",
        name: "encodedTransactions",
        type: "bytes[]",
      },
      {
        components: [
          {
            internalType: "bytes32",
            name: "root",
            type: "bytes32",
          },
          {
            components: [
              {
                internalType: "bytes32",
                name: "hash",
                type: "bytes32",
              },
              {
                internalType: "bool",
                name: "isLeft",
                type: "bool",
              },
            ],
            internalType: "struct IAttestcoinBlockProver.MerkleProofEntry[]",
            name: "siblings",
            type: "tuple[]",
          },
        ],
        internalType: "struct IAttestcoinBlockProver.MerkleProof[]",
        name: "merkleProofs",
        type: "tuple[]",
      },
      {
        components: [
          {
            internalType: "bytes32",
            name: "lowerEndpointDigest",
            type: "bytes32",
          },
          {
            internalType: "bytes32[]",
            name: "roots",
            type: "bytes32[]",
          },
        ],
        internalType: "struct IAttestcoinBlockProver.ContinuityProof",
        name: "sharedContinuityProof",
        type: "tuple",
      },
    ],
    name: "verifyAndEmit",
    outputs: [
      {
        internalType: "bool",
        name: "verified",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAttestcoinBlockProver__factory {
  static readonly abi = _abi;
  static createInterface(): IAttestcoinBlockProverInterface {
    return new Interface(_abi) as IAttestcoinBlockProverInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAttestcoinBlockProver {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IAttestcoinBlockProver;
  }
}
