/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IAttestcoinBlockProver__factory } from "./IAttestcoinBlockProver__factory";
export { IRemittanceCreditRegistry__factory } from "./IRemittanceCreditRegistry__factory";
