/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRemittanceCreditRegistry,
  IRemittanceCreditRegistryInterface,
} from "../../../contracts/interfaces/IRemittanceCreditRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "borrower",
        type: "address",
      },
      {
        internalType: "uint64",
        name: "lookbackWindowSeconds",
        type: "uint64",
      },
    ],
    name: "getStats",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "transferCount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "totalAmount",
            type: "uint256",
          },
          {
            internalType: "uint64",
            name: "firstTimestamp",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "lastTimestamp",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "avgIntervalSeconds",
            type: "uint64",
          },
          {
            internalType: "uint16",
            name: "intervalConsistencyBps",
            type: "uint16",
          },
        ],
        internalType: "struct IRemittanceCreditRegistry.RemittanceStats",
        name: "stats",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "borrower",
        type: "address",
      },
    ],
    name: "getTransfers",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "sender",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "amount",
            type: "uint256",
          },
          {
            internalType: "uint64",
            name: "sourceTimestamp",
            type: "uint64",
          },
          {
            internalType: "bytes32",
            name: "sourceTxHash",
            type: "bytes32",
          },
          {
            internalType: "uint64",
            name: "recordedAt",
            type: "uint64",
          },
        ],
        internalType: "struct IRemittanceCreditRegistry.VerifiedTransfer[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "sourceTxHash",
        type: "bytes32",
      },
    ],
    name: "isTransferRecorded",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "borrower",
        type: "address",
      },
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint64",
        name: "sourceTimestamp",
        type: "uint64",
      },
      {
        internalType: "bytes32",
        name: "sourceTxHash",
        type: "bytes32",
      },
    ],
    name: "recordVerifiedTransfer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IRemittanceCreditRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IRemittanceCreditRegistryInterface {
    return new Interface(_abi) as IRemittanceCreditRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IRemittanceCreditRegistry {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IRemittanceCreditRegistry;
  }
}
