/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MockAttestcoinBlockProver__factory } from "./MockAttestcoinBlockProver__factory";
export { MockStablecoin__factory } from "./MockStablecoin__factory";
