/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockAttestcoinBlockProver } from "./MockAttestcoinBlockProver";
export type { MockStablecoin } from "./MockStablecoin";
