/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IAttestcoinBlockProver {
  export type MerkleProofEntryStruct = { hash: BytesLike; isLeft: boolean };

  export type MerkleProofEntryStructOutput = [hash: string, isLeft: boolean] & {
    hash: string;
    isLeft: boolean;
  };

  export type MerkleProofStruct = {
    root: BytesLike;
    siblings: IAttestcoinBlockProver.MerkleProofEntryStruct[];
  };

  export type MerkleProofStructOutput = [
    root: string,
    siblings: IAttestcoinBlockProver.MerkleProofEntryStructOutput[]
  ] & {
    root: string;
    siblings: IAttestcoinBlockProver.MerkleProofEntryStructOutput[];
  };

  export type ContinuityProofStruct = {
    lowerEndpointDigest: BytesLike;
    roots: BytesLike[];
  };

  export type ContinuityProofStructOutput = [
    lowerEndpointDigest: string,
    roots: string[]
  ] & { lowerEndpointDigest: string; roots: string[] };
}

export interface MockAttestcoinBlockProverInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "owner"
      | "renounceOwnership"
      | "setVerified"
      | "transferOwnership"
      | "verifiedTxHashes"
      | "verify(uint64,uint64[],bytes[],(bytes32,(bytes32,bool)[])[],(bytes32,bytes32[]))"
      | "verify(uint64,uint64,bytes,(bytes32,(bytes32,bool)[]),(bytes32,bytes32[]))"
      | "verifyAndEmit(uint64,uint64,bytes,(bytes32,(bytes32,bool)[]),(bytes32,bytes32[]))"
      | "verifyAndEmit(uint64,uint64[],bytes[],(bytes32,(bytes32,bool)[])[],(bytes32,bytes32[]))"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "OwnershipTransferred" | "TransactionVerified"
  ): EventFragment;

  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setVerified",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifiedTxHashes",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verify(uint64,uint64[],bytes[],(bytes32,(bytes32,bool)[])[],(bytes32,bytes32[]))",
    values: [
      BigNumberish,
      BigNumberish[],
      BytesLike[],
      IAttestcoinBlockProver.MerkleProofStruct[],
      IAttestcoinBlockProver.ContinuityProofStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "verify(uint64,uint64,bytes,(bytes32,(bytes32,bool)[]),(bytes32,bytes32[]))",
    values: [
      BigNumberish,
      BigNumberish,
      BytesLike,
      IAttestcoinBlockProver.MerkleProofStruct,
      IAttestcoinBlockProver.ContinuityProofStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyAndEmit(uint64,uint64,bytes,(bytes32,(bytes32,bool)[]),(bytes32,bytes32[]))",
    values: [
      BigNumberish,
      BigNumberish,
      BytesLike,
      IAttestcoinBlockProver.MerkleProofStruct,
      IAttestcoinBlockProver.ContinuityProofStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyAndEmit(uint64,uint64[],bytes[],(bytes32,(bytes32,bool)[])[],(bytes32,bytes32[]))",
    values: [
      BigNumberish,
      BigNumberish[],
      BytesLike[],
      IAttestcoinBlockProver.MerkleProofStruct[],
      IAttestcoinBlockProver.ContinuityProofStruct
    ]
  ): string;

  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVerified",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifiedTxHashes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verify(uint64,uint64[],bytes[],(bytes32,(bytes32,bool)[])[],(bytes32,bytes32[]))",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verify(uint64,uint64,bytes,(bytes32,(bytes32,bool)[]),(bytes32,bytes32[]))",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyAndEmit(uint64,uint64,bytes,(bytes32,(bytes32,bool)[]),(bytes32,bytes32[]))",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyAndEmit(uint64,uint64[],bytes[],(bytes32,(bytes32,bool)[])[],(bytes32,bytes32[]))",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransactionVerifiedEvent {
  export type InputTuple = [
    chainKey: BigNumberish,
    height: BigNumberish,
    transactionIndex: BigNumberish
  ];
  export type OutputTuple = [
    chainKey: bigint,
    height: bigint,
    transactionIndex: bigint
  ];
  export interface OutputObject {
    chainKey: bigint;
    height: bigint;
    transactionIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MockAttestcoinBlockProver extends BaseContract {
  connect(runner?: ContractRunner | null): MockAttestcoinBlockProver;
  waitForDeployment(): Promise<this>;

  interface: MockAttestcoinBlockProverInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setVerified: TypedContractMethod<
    [encodedTx: BytesLike, isVerified: boolean],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verifiedTxHashes: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  "verify(uint64,uint64[],bytes[],(bytes32,(bytes32,bool)[])[],(bytes32,bytes32[]))": TypedContractMethod<
    [
      arg0: BigNumberish,
      arg1: BigNumberish[],
      encodedTransactions: BytesLike[],
      arg3: IAttestcoinBlockProver.MerkleProofStruct[],
      arg4: IAttestcoinBlockProver.ContinuityProofStruct
    ],
    [boolean],
    "view"
  >;

  "verify(uint64,uint64,bytes,(bytes32,(bytes32,bool)[]),(bytes32,bytes32[]))": TypedContractMethod<
    [
      arg0: BigNumberish,
      arg1: BigNumberish,
      encodedTransaction: BytesLike,
      arg3: IAttestcoinBlockProver.MerkleProofStruct,
      arg4: IAttestcoinBlockProver.ContinuityProofStruct
    ],
    [boolean],
    "view"
  >;

  "verifyAndEmit(uint64,uint64,bytes,(bytes32,(bytes32,bool)[]),(bytes32,bytes32[]))": TypedContractMethod<
    [
      chainKey: BigNumberish,
      height: BigNumberish,
      encodedTransaction: BytesLike,
      arg3: IAttestcoinBlockProver.MerkleProofStruct,
      arg4: IAttestcoinBlockProver.ContinuityProofStruct
    ],
    [boolean],
    "nonpayable"
  >;

  "verifyAndEmit(uint64,uint64[],bytes[],(bytes32,(bytes32,bool)[])[],(bytes32,bytes32[]))": TypedContractMethod<
    [
      chainKey: BigNumberish,
      heights: BigNumberish[],
      encodedTransactions: BytesLike[],
      arg3: IAttestcoinBlockProver.MerkleProofStruct[],
      arg4: IAttestcoinBlockProver.ContinuityProofStruct
    ],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVerified"
  ): TypedContractMethod<
    [encodedTx: BytesLike, isVerified: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifiedTxHashes"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "verify(uint64,uint64[],bytes[],(bytes32,(bytes32,bool)[])[],(bytes32,bytes32[]))"
  ): TypedContractMethod<
    [
      arg0: BigNumberish,
      arg1: BigNumberish[],
      encodedTransactions: BytesLike[],
      arg3: IAttestcoinBlockProver.MerkleProofStruct[],
      arg4: IAttestcoinBlockProver.ContinuityProofStruct
    ],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "verify(uint64,uint64,bytes,(bytes32,(bytes32,bool)[]),(bytes32,bytes32[]))"
  ): TypedContractMethod<
    [
      arg0: BigNumberish,
      arg1: BigNumberish,
      encodedTransaction: BytesLike,
      arg3: IAttestcoinBlockProver.MerkleProofStruct,
      arg4: IAttestcoinBlockProver.ContinuityProofStruct
    ],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifyAndEmit(uint64,uint64,bytes,(bytes32,(bytes32,bool)[]),(bytes32,bytes32[]))"
  ): TypedContractMethod<
    [
      chainKey: BigNumberish,
      height: BigNumberish,
      encodedTransaction: BytesLike,
      arg3: IAttestcoinBlockProver.MerkleProofStruct,
      arg4: IAttestcoinBlockProver.ContinuityProofStruct
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyAndEmit(uint64,uint64[],bytes[],(bytes32,(bytes32,bool)[])[],(bytes32,bytes32[]))"
  ): TypedContractMethod<
    [
      chainKey: BigNumberish,
      heights: BigNumberish[],
      encodedTransactions: BytesLike[],
      arg3: IAttestcoinBlockProver.MerkleProofStruct[],
      arg4: IAttestcoinBlockProver.ContinuityProofStruct
    ],
    [boolean],
    "nonpayable"
  >;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TransactionVerified"
  ): TypedContractEvent<
    TransactionVerifiedEvent.InputTuple,
    TransactionVerifiedEvent.OutputTuple,
    TransactionVerifiedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TransactionVerified(uint64,uint64,uint64)": TypedContractEvent<
      TransactionVerifiedEvent.InputTuple,
      TransactionVerifiedEvent.OutputTuple,
      TransactionVerifiedEvent.OutputObject
    >;
    TransactionVerified: TypedContractEvent<
      TransactionVerifiedEvent.InputTuple,
      TransactionVerifiedEvent.OutputTuple,
      TransactionVerifiedEvent.OutputObject
    >;
  };
}
